#!/bin/bash
# KOSPI 시가총액 상위 기업 복지 파싱 명령어 (Claude Code에서 실행)
# Usage: 개별 라인을 복사하여 Claude Code에서 실행
# 생성일: 2026-03-26

# ━━ KOSPI TOP 100 (우선주/중복 제외) ━━

/parse-benefits 삼성전자
/parse-benefits SK하이닉스
/parse-benefits LG에너지솔루션
/parse-benefits 삼성바이오로직스
/parse-benefits 현대자동차
/parse-benefits HD현대중공업
/parse-benefits SK스퀘어
/parse-benefits 한화에어로스페이스
/parse-benefits 두산에너빌리티
/parse-benefits KB금융
/parse-benefits 기아
/parse-benefits 셀트리온
/parse-benefits 삼성물산
/parse-benefits NAVER
/parse-benefits 신한지주
/parse-benefits 한화오션
/parse-benefits 현대모비스
/parse-benefits 삼성생명
/parse-benefits 한국전력
/parse-benefits HD한국조선해양
/parse-benefits HD현대일렉트릭
/parse-benefits 카카오
/parse-benefits 하나금융지주
/parse-benefits POSCO홀딩스
/parse-benefits 고려아연
/parse-benefits 알테오젠
/parse-benefits LG화학
/parse-benefits 삼성화재
/parse-benefits 삼성SDI
/parse-benefits 삼성중공업
/parse-benefits 우리금융지주
/parse-benefits 현대로템
/parse-benefits 메리츠금융지주
/parse-benefits HMM
/parse-benefits 삼성전기
/parse-benefits SK
/parse-benefits SK이노베이션
/parse-benefits KT&G
/parse-benefits IBK기업은행
/parse-benefits 포스코퓨처엠
/parse-benefits 효성중공업
/parse-benefits LG전자
/parse-benefits HD현대
/parse-benefits 에코프로비엠
/parse-benefits 하이브
/parse-benefits LS ELECTRIC
/parse-benefits 현대글로비스
/parse-benefits 삼성SDS
/parse-benefits KT
/parse-benefits 미래에셋증권
/parse-benefits 두산
/parse-benefits LG
/parse-benefits 한미반도체
/parse-benefits 크래프톤
/parse-benefits SK텔레콤
/parse-benefits 한국항공우주산업
/parse-benefits 에이비엘바이오
/parse-benefits 카카오뱅크
/parse-benefits 한화시스템
/parse-benefits SK바이오팜
/parse-benefits S-Oil
/parse-benefits DB손해보험
/parse-benefits 삼양식품
/parse-benefits LIG넥스원
/parse-benefits 레인보우로보틱스
/parse-benefits 현대오토에버
/parse-benefits 한국금융지주
/parse-benefits 유한양행
/parse-benefits 이수페타시스
/parse-benefits 포스코인터내셔널
/parse-benefits HD현대마린솔루션
/parse-benefits 에이피알
/parse-benefits 대한항공
/parse-benefits 한진칼
/parse-benefits 현대건설
/parse-benefits 키움증권
/parse-benefits NH투자증권
/parse-benefits 한국타이어앤테크놀로지
/parse-benefits 아모레퍼시픽
/parse-benefits 삼성증권
/parse-benefits 카카오페이
/parse-benefits 삼성카드
/parse-benefits LG이노텍
/parse-benefits LS
/parse-benefits LG유플러스
/parse-benefits 코웨이
/parse-benefits 한화
/parse-benefits LG씨엔에스
/parse-benefits LG디스플레이
/parse-benefits 한미약품
/parse-benefits 두산밥캣
/parse-benefits 삼성에피스홀딩스
/parse-benefits 현대제철
/parse-benefits 롯데케미칼
