#!/bin/bash
# KOSDAQ 시가총액 상위 기업 복지 파싱 명령어 (Claude Code에서 실행)
# Usage: 개별 라인을 복사하여 Claude Code에서 실행
# 생성일: 2026-03-26

# ━━ KOSDAQ TOP 100 ━━

/parse-benefits 에코프로
/parse-benefits 알테오젠
/parse-benefits 에코프로비엠
/parse-benefits 삼천당제약
/parse-benefits 레인보우로보틱스
/parse-benefits 에이비엘바이오
/parse-benefits 코오롱티슈진
/parse-benefits 케어젠
/parse-benefits 리노공업
/parse-benefits HLB
/parse-benefits 리가켐바이오
/parse-benefits 펩트론
/parse-benefits 디앤디파마텍
/parse-benefits 보로노이
/parse-benefits 파마리서치
/parse-benefits 원익IPS
/parse-benefits 클래시스
/parse-benefits 메지온
/parse-benefits 이오테크닉스
/parse-benefits 로보티즈
/parse-benefits HPSP
/parse-benefits ISC
/parse-benefits 오스코텍
/parse-benefits 에이피알
/parse-benefits 한솔케미칼
/parse-benefits 올릭스
/parse-benefits 엘앤씨바이오
/parse-benefits 테크윙
/parse-benefits 휴젤
/parse-benefits 솔브레인
/parse-benefits 유진테크
/parse-benefits 파크시스템스
/parse-benefits 덕산네오룩스
/parse-benefits 에이디테크놀로지
/parse-benefits 티씨케이
/parse-benefits 피에스케이
/parse-benefits 주성엔지니어링
/parse-benefits 셀트리온제약
/parse-benefits 심텍
/parse-benefits HLB생명과학
/parse-benefits 동국제약
/parse-benefits 네패스
/parse-benefits 씨젠
/parse-benefits 성일하이텍
/parse-benefits SM엔터테인먼트
/parse-benefits 인터로조
/parse-benefits CJ ENM
/parse-benefits 비에이치
/parse-benefits JYP엔터테인먼트
/parse-benefits 실리콘투
/parse-benefits 위메이드
/parse-benefits 카카오게임즈
/parse-benefits HLB테라퓨틱스
/parse-benefits HLB이노베이션
/parse-benefits 컴투스
/parse-benefits 펄어비스
/parse-benefits 솔브레인홀딩스
/parse-benefits 나노엔텍
/parse-benefits 다우데이타
/parse-benefits HLB제약
/parse-benefits 엠씨넥스
/parse-benefits 서울반도체
/parse-benefits 코미팜
/parse-benefits 더블유게임즈
/parse-benefits 에스티큐브
/parse-benefits 네오위즈
/parse-benefits 피에스케이홀딩스
/parse-benefits 제이엘케이
/parse-benefits 나노신소재
/parse-benefits 엠투아이
/parse-benefits 티에스이
/parse-benefits 원익QnC
/parse-benefits 케이엠더블유
/parse-benefits 에코프로에이치엔
/parse-benefits 셀리드
/parse-benefits 와이바이오로직스
/parse-benefits 루닛
/parse-benefits 엔켐
/parse-benefits 제넥신
/parse-benefits 에임드바이오
/parse-benefits GC녹십자셀
/parse-benefits 엘오티베큠
/parse-benefits 동화기업
/parse-benefits 아이패밀리에스씨
/parse-benefits 켐트로스
/parse-benefits 선익시스템
/parse-benefits 앱클론
/parse-benefits 지놈앤컴퍼니
/parse-benefits 에스에프에이
/parse-benefits 아이센스
/parse-benefits 텔레칩스
/parse-benefits 바이넥스
/parse-benefits 켐트로닉스
/parse-benefits 매커스
/parse-benefits 리메드
/parse-benefits 유비쿼스홀딩스
/parse-benefits 원방테크
/parse-benefits 코오롱인더스트리FnC
/parse-benefits 현대무벡스
/parse-benefits 노바텍
