#!/bin/bash
# KOSDAQ 시가총액 상위 기업 복지 페이지 스크래핑 명령어
# Usage: 개별 라인을 복사하여 터미널에서 실행
# 생성일: 2026-03-26

# ━━ KOSDAQ TOP 100 ━━

server/tools/.venv/bin/python server/tools/scrape_benefits.py "에코프로" --url "https://ecoprogroup.recruiter.co.kr/career/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "알테오젠" --url "https://www.alteogen.com/kr/sub/careers/recruit.php" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에코프로비엠" --url "https://ecoprorecruit.co.kr" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "삼천당제약" --url "http://www.scd.co.kr/recruit/recruit/index.jsp" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "레인보우로보틱스" --url "https://www.rainbow-robotics.com/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에이비엘바이오" --url "https://ablbio.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "코오롱티슈진" --url "https://dream.kolon.com" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "케어젠" --url "https://www.jobkorea.co.kr/company/16152504/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "리노공업" --url "https://leeno.com/kr/careers/career1/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HLB" --url "https://hlb-group.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "리가켐바이오" --url "https://ligachembio.ninehire.site/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "펩트론" --url "http://www.peptron.co.kr/job.html" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "디앤디파마텍" --url "http://ddpharmatech.com/m15.php" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "보로노이" --url "https://voronoi.career.greetinghr.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "파마리서치" --url "https://pharmaresearch.co.kr/sub/career/list.html" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "원익IPS" --url "https://www.careers-page.com/wonik-ips" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "클래시스" --url "https://classys.co.kr/careers/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "메지온" --url "http://www.mezzion.co.kr" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "이오테크닉스" --url "http://www.eotechnics.com/page/company/employment2.php" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "로보티즈" --url "https://www.robotis.com/model/board.php?bo_table=recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HPSP" --url "https://thehpsp.com/ko/bbs/board.php?bo_table=career" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "ISC" --url "https://www.isc21.kr/main/careers.html" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "오스코텍" --url "https://oscotec.com/Careers" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에이피알" --url "https://apr-careers.com/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "한솔케미칼" --url "https://hansolchemical.careerlink.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "올릭스" --url "https://olixpharma.career.greetinghr.com/ko/intro" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "엘앤씨바이오" --url "https://lncbio.career.greetinghr.com/en/intro" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "테크윙" --url "https://techwing.recruiter.co.kr/career/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "휴젤" --url "https://hugel.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "솔브레인" --url "https://career.soulbrain.co.kr" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "유진테크" --url "https://www.eugenetech.co.kr/recruit/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "파크시스템스" --url "https://www.parksystems.com/kr/company/career" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "덕산네오룩스" --url "https://www.dsnl.co.kr/recruit_04.aspx" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에이디테크놀로지" --url "https://recruit.adtek.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "티씨케이" --url "https://tck.recruiter.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "피에스케이" --url "https://psk.recruiter.co.kr/career/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "주성엔지니어링" --url "https://jusung.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "셀트리온제약" --url "https://recruit.celltrionph.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "심텍" --url "https://www.simmtech.com/recruit/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HLB생명과학" --url "https://hlb-group.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "동국제약" --url "https://dkpharm.recruiter.co.kr/career/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "네패스" --url "https://careers.nepes.co.kr/nepesrecruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "씨젠" --url "https://seegene.recruiter.co.kr/career/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "성일하이텍" --url "https://www.sungeelht.com/recruit/list/24" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "SM엔터테인먼트" --url "https://recruit.smentertainment.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "인터로조" --url "https://www.interojo.com/aboutus/recruitment/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "CJ ENM" --url "https://recruit.cjenm.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "비에이치" --url "https://www.bhflex.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "JYP엔터테인먼트" --url "https://recruit.jype.com/Recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "실리콘투" --url "https://www.siliconii.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "위메이드" --url "https://recruit.wemade.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "카카오게임즈" --url "https://recruit.kakaogames.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HLB테라퓨틱스" --url "https://hlb-group.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HLB이노베이션" --url "https://hlb-group.career.greetinghr.com/ko/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "컴투스" --url "https://com2us.recruiter.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "펄어비스" --url "https://www.pearlabyss.com/ko-KR/Company/Careers/Intro" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "솔브레인홀딩스" --url "https://career.soulbrain.co.kr" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "나노엔텍" --url "https://www.jobkorea.co.kr/company/1600792/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "다우데이타" --url "https://www.daoudata.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "HLB제약" --url "https://www.hlbpharma.co.kr/sub_recruit/list.php" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "엠씨넥스" --url "https://www.mcnex.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "서울반도체" --url "https://www.seoulsemicon.com/kr/career/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "코미팜" --url "https://www.komipharm.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "더블유게임즈" --url "https://www.doubleugames.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에스티큐브" --url "https://www.stcube.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "네오위즈" --url "https://corp.neowiz.com/recruit" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "피에스케이홀딩스" --url "https://psk.recruiter.co.kr/career/home" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "제이엘케이" --url "https://www.jlk.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "나노신소재" --url "https://www.anonm.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "엠투아이" --url "https://www.m2i.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "티에스이" --url "https://www.tse21.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "원익QnC" --url "https://www.wonikqnc.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "케이엠더블유" --url "https://www.kmw.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에코프로에이치엔" --url "https://ecoprorecruit.co.kr" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "셀리드" --url "https://www.cellid.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "와이바이오로직스" --url "https://www.ybiologics.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "루닛" --url "https://www.lunit.io/ko/careers" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "엔켐" --url "https://www.enchem.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "제넥신" --url "https://www.genexine.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에임드바이오" --url "https://www.aimedbio.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "GC녹십자셀" --url "https://www.gccell.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "엘오티베큠" --url "https://www.lotvacuum.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "동화기업" --url "https://www.dongwha.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "아이패밀리에스씨" --url "https://www.ifamilysc.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "켐트로스" --url "https://www.chemtros.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "선익시스템" --url "https://www.sunic.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "앱클론" --url "https://www.abclon.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "지놈앤컴퍼니" --url "https://www.genomenc.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "에스에프에이" --url "https://www.sfa.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "아이센스" --url "https://www.i-sens.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "텔레칩스" --url "https://www.telechips.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "바이넥스" --url "https://www.binex.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "켐트로닉스" --url "https://www.chemtronics.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "매커스" --url "https://www.makersi.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "리메드" --url "https://www.remed.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "유비쿼스홀딩스" --url "https://www.ubiquoss.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "원방테크" --url "https://www.wonbangtech.co.kr/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "코오롱인더스트리FnC" --url "https://recruit.kolonfnc.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "현대무벡스" --url "https://www.hyundaimuvex.com/" --raw-only
server/tools/.venv/bin/python server/tools/scrape_benefits.py "노바텍" --url "https://www.novatech.co.kr/" --raw-only
