# KOSDAQ 시가총액 상위 51~100 회사 데이터
KOSDAQ_2 = [
    {"id": "wemade", "name": "위메이드", "aliases": ["위메이드", "Wemade"], "type": "mid", "industry": "게임", "logo": "WM"},
    {"id": "kakao_games", "name": "카카오게임즈", "aliases": ["카카오게임즈", "Kakao Games"], "type": "large", "industry": "게임", "logo": "KG"},
    {"id": "hlb_thera", "name": "HLB테라퓨틱스", "aliases": ["HLB테라퓨틱스", "HLB Therapeutics"], "type": "mid", "industry": "바이오", "logo": "HT"},
    {"id": "hlb_inno", "name": "HLB이노베이션", "aliases": ["HLB이노베이션", "HLB Innovation"], "type": "mid", "industry": "바이오", "logo": "HI"},
    {"id": "com2us", "name": "컴투스", "aliases": ["컴투스", "Com2uS"], "type": "mid", "industry": "게임", "logo": "C2"},
    {"id": "pearl_abyss", "name": "펄어비스", "aliases": ["펄어비스", "Pearl Abyss", "검은사막"], "type": "mid", "industry": "게임", "logo": "PA"},
    {"id": "soulbrain_hd", "name": "솔브레인홀딩스", "aliases": ["솔브레인홀딩스", "Soulbrain Holdings"], "type": "mid", "industry": "반도체소재/지주", "logo": "SH"},
    {"id": "nano_entek", "name": "나노엔텍", "aliases": ["나노엔텍", "NanoEntek"], "type": "mid", "industry": "바이오/진단", "logo": "NE"},
    {"id": "daou_data", "name": "다우데이타", "aliases": ["다우데이타", "Daou Data"], "type": "mid", "industry": "IT서비스", "logo": "DD"},
    {"id": "hlb_pharma", "name": "HLB제약", "aliases": ["HLB제약", "HLB Pharma"], "type": "mid", "industry": "제약", "logo": "HP"},
    {"id": "mcnex", "name": "엠씨넥스", "aliases": ["엠씨넥스", "MCNEX"], "type": "mid", "industry": "카메라모듈", "logo": "MC"},
    {"id": "seoul_semi", "name": "서울반도체", "aliases": ["서울반도체", "Seoul Semiconductor"], "type": "mid", "industry": "LED/반도체", "logo": "SS"},
    {"id": "komipharm", "name": "코미팜", "aliases": ["코미팜", "Komipharm"], "type": "mid", "industry": "바이오/동물약품", "logo": "KM"},
    {"id": "doubleugames", "name": "더블유게임즈", "aliases": ["더블유게임즈", "DoubleUGames"], "type": "mid", "industry": "게임/소셜카지노", "logo": "DU"},
    {"id": "st_cube", "name": "에스티큐브", "aliases": ["에스티큐브", "STCube"], "type": "mid", "industry": "바이오/항암", "logo": "ST"},
    {"id": "neowiz", "name": "네오위즈", "aliases": ["네오위즈", "Neowiz"], "type": "mid", "industry": "게임", "logo": "NW"},
    {"id": "psk_holdings", "name": "피에스케이홀딩스", "aliases": ["피에스케이홀딩스", "PSK Holdings"], "type": "mid", "industry": "반도체장비/지주", "logo": "PH"},
    {"id": "jlk", "name": "제이엘케이", "aliases": ["제이엘케이", "JLK"], "type": "mid", "industry": "AI/의료영상", "logo": "JL"},
    {"id": "nano_material", "name": "나노신소재", "aliases": ["나노신소재", "Nano"], "type": "mid", "industry": "2차전지소재", "logo": "NM"},
    {"id": "m2i", "name": "엠투아이", "aliases": ["엠투아이", "M2I"], "type": "mid", "industry": "산업자동화", "logo": "M2"},
    {"id": "tse", "name": "티에스이", "aliases": ["티에스이", "TSE"], "type": "mid", "industry": "반도체검사", "logo": "TS"},
    {"id": "wonik_qnc", "name": "원익QnC", "aliases": ["원익QnC", "Wonik QnC"], "type": "mid", "industry": "반도체소재", "logo": "WQ"},
    {"id": "kmw", "name": "케이엠더블유", "aliases": ["케이엠더블유", "KMW"], "type": "mid", "industry": "5G/통신장비", "logo": "KM"},
    {"id": "ecopro_hn", "name": "에코프로에이치엔", "aliases": ["에코프로에이치엔", "EcoPro HN"], "type": "mid", "industry": "환경/2차전지", "logo": "EH"},
    {"id": "cellid", "name": "셀리드", "aliases": ["셀리드", "Cellid"], "type": "mid", "industry": "바이오/백신", "logo": "CD"},
    {"id": "y_biologics", "name": "와이바이오로직스", "aliases": ["와이바이오로직스", "Y-Biologics"], "type": "mid", "industry": "바이오/항체", "logo": "YB"},
    {"id": "lunit", "name": "루닛", "aliases": ["루닛", "Lunit"], "type": "mid", "industry": "AI/의료영상", "logo": "LU"},
    {"id": "enchem", "name": "엔켐", "aliases": ["엔켐", "Enchem"], "type": "mid", "industry": "2차전지전해액", "logo": "EC"},
    {"id": "genexine", "name": "제넥신", "aliases": ["제넥신", "Genexine"], "type": "mid", "industry": "바이오/유전자치료", "logo": "GX"},
    {"id": "aimed_bio", "name": "에임드바이오", "aliases": ["에임드바이오", "AimedBio"], "type": "mid", "industry": "바이오/제약", "logo": "AM"},
    {"id": "gc_cell", "name": "GC녹십자셀", "aliases": ["GC녹십자셀", "GC Cell"], "type": "mid", "industry": "바이오/세포치료", "logo": "GC"},
    {"id": "lot_vacuum", "name": "엘오티베큠", "aliases": ["엘오티베큠", "LOT Vacuum"], "type": "mid", "industry": "반도체장비", "logo": "LV"},
    {"id": "dongwha", "name": "동화기업", "aliases": ["동화기업", "Dongwha"], "type": "mid", "industry": "건자재/화학", "logo": "DW"},
    {"id": "ifamily", "name": "아이패밀리에스씨", "aliases": ["아이패밀리에스씨", "iFamily SC", "롬앤"], "type": "mid", "industry": "뷰티/화장품", "logo": "IF"},
    {"id": "chemtros", "name": "켐트로스", "aliases": ["켐트로스", "Chemtros"], "type": "mid", "industry": "정밀화학", "logo": "CR"},
    {"id": "sunic_system", "name": "선익시스템", "aliases": ["선익시스템", "Sunic System"], "type": "mid", "industry": "OLED장비", "logo": "SN"},
    {"id": "abclon", "name": "앱클론", "aliases": ["앱클론", "AbClon"], "type": "mid", "industry": "바이오/항체", "logo": "AC"},
    {"id": "genome_company", "name": "지놈앤컴퍼니", "aliases": ["지놈앤컴퍼니", "Genome & Company"], "type": "mid", "industry": "바이오/마이크로바이옴", "logo": "GN"},
    {"id": "sfa", "name": "에스에프에이", "aliases": ["에스에프에이", "SFA"], "type": "mid", "industry": "디스플레이장비", "logo": "SF"},
    {"id": "i_sens", "name": "아이센스", "aliases": ["아이센스", "i-SENS"], "type": "mid", "industry": "의료기기/진단", "logo": "IS"},
    {"id": "telechips", "name": "텔레칩스", "aliases": ["텔레칩스", "Telechips"], "type": "mid", "industry": "차량용반도체", "logo": "TC"},
    {"id": "binex", "name": "바이넥스", "aliases": ["바이넥스", "Binex"], "type": "mid", "industry": "바이오/CMO", "logo": "BN"},
    {"id": "chemtronics", "name": "켐트로닉스", "aliases": ["켐트로닉스", "Chemtronics"], "type": "mid", "industry": "전자부품", "logo": "CM"},
    {"id": "makersi", "name": "매커스", "aliases": ["매커스", "Makersi"], "type": "mid", "industry": "반도체장비", "logo": "MK"},
    {"id": "remed", "name": "리메드", "aliases": ["리메드", "Remed"], "type": "mid", "industry": "의료기기/뇌자극", "logo": "RM"},
    {"id": "ubiquoss", "name": "유비쿼스홀딩스", "aliases": ["유비쿼스", "Ubiquoss"], "type": "mid", "industry": "네트워크장비", "logo": "UB"},
    {"id": "wonbang_tech", "name": "원방테크", "aliases": ["원방테크", "WonbangTech"], "type": "mid", "industry": "반도체장비", "logo": "WB"},
    {"id": "kolon_fnc", "name": "코오롱인더스트리 FnC", "aliases": ["코오롱FnC", "Kolon FnC"], "type": "mid", "industry": "패션/의류", "logo": "KF"},
    {"id": "hyundai_muvex", "name": "현대무벡스", "aliases": ["현대무벡스", "Hyundai Muvex"], "type": "mid", "industry": "물류자동화", "logo": "HX"},
    {"id": "novatech", "name": "노바텍", "aliases": ["노바텍", "Novatech"], "type": "mid", "industry": "반도체/전자", "logo": "NV"},
]
