# KOSPI 시가총액 상위 51~100 회사 데이터
KOSPI_2 = [
    {"id": "doosan", "name": "두산", "aliases": ["두산", "Doosan"], "type": "large", "industry": "지주/중공업", "logo": "DS"},
    {"id": "lg_corp", "name": "LG", "aliases": ["LG", "엘지", "LG그룹"], "type": "large", "industry": "지주", "logo": "LG"},
    {"id": "ecopro", "name": "에코프로", "aliases": ["에코프로", "EcoPro"], "type": "mid", "industry": "2차전지소재", "logo": "EP"},
    {"id": "hanmi_semi", "name": "한미반도체", "aliases": ["한미반도체", "Hanmi Semiconductor"], "type": "mid", "industry": "반도체장비", "logo": "HS"},
    {"id": "krafton", "name": "크래프톤", "aliases": ["크래프톤", "KRAFTON", "배틀그라운드"], "type": "large", "industry": "게임", "logo": "KR"},
    {"id": "skt", "name": "SK텔레콤", "aliases": ["SK텔레콤", "SKT", "에스케이텔레콤"], "type": "large", "industry": "통신", "logo": "ST"},
    {"id": "kai", "name": "한국항공우주산업", "aliases": ["한국항공우주산업", "KAI", "한국항공"], "type": "large", "industry": "방산/항공", "logo": "KA"},
    {"id": "abl_bio", "name": "에이비엘바이오", "aliases": ["에이비엘바이오", "ABL Bio"], "type": "mid", "industry": "바이오/제약", "logo": "AB"},
    {"id": "kakao_bank", "name": "카카오뱅크", "aliases": ["카카오뱅크", "KakaoBank"], "type": "large", "industry": "인터넷은행", "logo": "KB"},
    {"id": "hanwha_systems", "name": "한화시스템", "aliases": ["한화시스템", "Hanwha Systems"], "type": "large", "industry": "방산/IT", "logo": "HS"},
    {"id": "sk_biopharm", "name": "SK바이오팜", "aliases": ["SK바이오팜", "SK Biopharmaceuticals"], "type": "large", "industry": "바이오/제약", "logo": "SB"},
    {"id": "s_oil", "name": "S-Oil", "aliases": ["S-Oil", "에쓰오일", "에스오일"], "type": "large", "industry": "정유", "logo": "SO"},
    {"id": "db_insurance", "name": "DB손해보험", "aliases": ["DB손해보험", "DB손보", "동부화재"], "type": "large", "industry": "보험", "logo": "DB"},
    {"id": "samyang_food", "name": "삼양식품", "aliases": ["삼양식품", "삼양라면", "불닭볶음면"], "type": "mid", "industry": "식품", "logo": "SY"},
    {"id": "lig_nex1", "name": "LIG넥스원", "aliases": ["LIG넥스원", "LIG Nex1"], "type": "large", "industry": "방산", "logo": "LN"},
    {"id": "rainbow_robotics", "name": "레인보우로보틱스", "aliases": ["레인보우로보틱스", "Rainbow Robotics"], "type": "mid", "industry": "로봇", "logo": "RR"},
    {"id": "hyundai_autoever", "name": "현대오토에버", "aliases": ["현대오토에버", "Hyundai AutoEver"], "type": "large", "industry": "IT서비스", "logo": "HA"},
    {"id": "kolon_tissuegene", "name": "코오롱티슈진", "aliases": ["코오롱티슈진", "Kolon TissueGene"], "type": "mid", "industry": "바이오", "logo": "KT"},
    {"id": "yuhan", "name": "유한양행", "aliases": ["유한양행", "Yuhan"], "type": "large", "industry": "제약", "logo": "YH"},
    {"id": "isu_petasys", "name": "이수페타시스", "aliases": ["이수페타시스", "ISU Petasys"], "type": "mid", "industry": "전자부품/PCB", "logo": "IP"},
    {"id": "posco_intl", "name": "포스코인터내셔널", "aliases": ["포스코인터내셔널", "POSCO International"], "type": "large", "industry": "무역/에너지", "logo": "PI"},
    {"id": "hd_marine", "name": "HD현대마린솔루션", "aliases": ["HD현대마린솔루션", "HD현대마린"], "type": "large", "industry": "조선서비스", "logo": "HM"},
    {"id": "apr", "name": "에이피알", "aliases": ["에이피알", "APR", "메디큐브"], "type": "mid", "industry": "뷰티/화장품", "logo": "AP"},
    {"id": "korean_air", "name": "대한항공", "aliases": ["대한항공", "Korean Air"], "type": "large", "industry": "항공", "logo": "KE"},
    {"id": "hanjin_kal", "name": "한진칼", "aliases": ["한진칼", "Hanjin Kal"], "type": "large", "industry": "지주/항공", "logo": "HJ"},
    {"id": "hyundai_enc", "name": "현대건설", "aliases": ["현대건설", "Hyundai E&C"], "type": "large", "industry": "건설", "logo": "HC"},
    {"id": "kiwoom", "name": "키움증권", "aliases": ["키움증권", "Kiwoom"], "type": "large", "industry": "증권", "logo": "KW"},
    {"id": "nh_invest", "name": "NH투자증권", "aliases": ["NH투자증권", "NH투자"], "type": "large", "industry": "증권", "logo": "NH"},
    {"id": "hankook_tire", "name": "한국타이어앤테크놀로지", "aliases": ["한국타이어", "Hankook Tire"], "type": "large", "industry": "타이어", "logo": "HT"},
    {"id": "amorepacific", "name": "아모레퍼시픽", "aliases": ["아모레퍼시픽", "아모레", "Amorepacific"], "type": "large", "industry": "화장품", "logo": "AP"},
    {"id": "samsung_securities", "name": "삼성증권", "aliases": ["삼성증권", "Samsung Securities"], "type": "large", "industry": "증권", "logo": "SS"},
    {"id": "hlb", "name": "HLB", "aliases": ["HLB", "에이치엘비"], "type": "mid", "industry": "바이오/제약", "logo": "HL"},
    {"id": "kakao_pay", "name": "카카오페이", "aliases": ["카카오페이", "KakaoPay"], "type": "large", "industry": "핀테크", "logo": "KP"},
    {"id": "samsung_card", "name": "삼성카드", "aliases": ["삼성카드", "Samsung Card"], "type": "large", "industry": "금융/카드", "logo": "SC"},
    {"id": "lg_innotek", "name": "LG이노텍", "aliases": ["LG이노텍", "LG Innotek"], "type": "large", "industry": "전자부품", "logo": "LI"},
    {"id": "ligachem", "name": "리가켐바이오", "aliases": ["리가켐바이오", "LigaChem Bio"], "type": "mid", "industry": "바이오/제약", "logo": "LB"},
    {"id": "ls_corp", "name": "LS", "aliases": ["LS", "엘에스"], "type": "large", "industry": "전선/지주", "logo": "LS"},
    {"id": "lg_uplus", "name": "LG유플러스", "aliases": ["LG유플러스", "LG U+", "엘지유플러스"], "type": "large", "industry": "통신", "logo": "LU"},
    {"id": "coway", "name": "코웨이", "aliases": ["코웨이", "Coway"], "type": "large", "industry": "생활가전/렌탈", "logo": "CW"},
    {"id": "hanwha_corp", "name": "한화", "aliases": ["한화", "Hanwha", "한화그룹"], "type": "large", "industry": "방산/화학/지주", "logo": "HW"},
    {"id": "lg_cns", "name": "LG씨엔에스", "aliases": ["LG CNS", "LG씨엔에스", "엘지씨엔에스"], "type": "large", "industry": "IT서비스", "logo": "LC"},
    {"id": "peptron", "name": "펩트론", "aliases": ["펩트론", "Peptron"], "type": "mid", "industry": "바이오/제약", "logo": "PT"},
    {"id": "lg_display", "name": "LG디스플레이", "aliases": ["LG디스플레이", "LGD", "LG Display"], "type": "large", "industry": "디스플레이", "logo": "LD"},
    {"id": "hanmi_pharm", "name": "한미약품", "aliases": ["한미약품", "Hanmi Pharm"], "type": "large", "industry": "제약", "logo": "HP"},
    {"id": "doosan_bobcat", "name": "두산밥캣", "aliases": ["두산밥캣", "Doosan Bobcat"], "type": "large", "industry": "건설기계", "logo": "DB"},
    {"id": "samchundang", "name": "삼천당제약", "aliases": ["삼천당제약", "삼천당", "Samchundang"], "type": "mid", "industry": "제약", "logo": "SD"},
    {"id": "korea_financial", "name": "한국금융지주", "aliases": ["한국금융지주", "한국투자증권"], "type": "large", "industry": "금융/증권", "logo": "KF"},
    {"id": "samsung_epis", "name": "삼성에피스홀딩스", "aliases": ["삼성에피스", "Samsung FEIS"], "type": "large", "industry": "지주", "logo": "SE"},
    {"id": "hyundai_steel", "name": "현대제철", "aliases": ["현대제철", "Hyundai Steel"], "type": "large", "industry": "철강", "logo": "HS"},
    {"id": "lotte_chem", "name": "롯데케미칼", "aliases": ["롯데케미칼", "Lotte Chemical"], "type": "large", "industry": "화학", "logo": "LC"},
]
