# KOSPI 시가총액 상위 1~50 회사 데이터
KOSPI_1 = [
    {"id": "samsung_elec", "name": "삼성전자", "aliases": ["삼성전자", "Samsung", "삼성", "samsung"], "type": "large", "industry": "반도체/전자", "logo": "SE"},
    {"id": "sk_hynix", "name": "SK하이닉스", "aliases": ["SK하이닉스", "하이닉스", "skhynix"], "type": "large", "industry": "반도체", "logo": "SK"},
    {"id": "lg_energy", "name": "LG에너지솔루션", "aliases": ["LG에너지솔루션", "LGES", "엘지에너지"], "type": "large", "industry": "2차전지", "logo": "LG"},
    {"id": "samsung_bio", "name": "삼성바이오로직스", "aliases": ["삼성바이오", "삼바", "Samsung Biologics"], "type": "large", "industry": "바이오/제약", "logo": "SB"},
    {"id": "hyundai_motor", "name": "현대자동차", "aliases": ["현대자동차", "현대차", "현차", "Hyundai"], "type": "large", "industry": "자동차", "logo": "H"},
    {"id": "hd_heavy", "name": "HD현대중공업", "aliases": ["HD현대중공업", "현대중공업", "HD중공업"], "type": "large", "industry": "조선/중공업", "logo": "HD"},
    {"id": "sk_square", "name": "SK스퀘어", "aliases": ["SK스퀘어", "sk square"], "type": "large", "industry": "투자/지주", "logo": "SK"},
    {"id": "hanwha_aero", "name": "한화에어로스페이스", "aliases": ["한화에어로스페이스", "한화에어로", "Hanwha Aerospace"], "type": "large", "industry": "방산/항공", "logo": "HW"},
    {"id": "doosan_enb", "name": "두산에너빌리티", "aliases": ["두산에너빌리티", "두산에너", "Doosan Enerbility"], "type": "large", "industry": "에너지/플랜트", "logo": "DS"},
    {"id": "kb_financial", "name": "KB금융", "aliases": ["KB금융", "KB", "국민은행", "KB국민은행"], "type": "large", "industry": "금융/은행", "logo": "KB"},
    {"id": "kia", "name": "기아", "aliases": ["기아", "기아차", "KIA", "Kia"], "type": "large", "industry": "자동차", "logo": "KI"},
    {"id": "celltrion", "name": "셀트리온", "aliases": ["셀트리온", "Celltrion"], "type": "large", "industry": "바이오/제약", "logo": "CT"},
    {"id": "samsung_cnt", "name": "삼성물산", "aliases": ["삼성물산", "Samsung C&T"], "type": "large", "industry": "건설/무역", "logo": "SC"},
    {"id": "naver", "name": "NAVER", "aliases": ["네이버", "NAVER", "naver", "NHN"], "type": "large", "industry": "IT/플랫폼", "logo": "N"},
    {"id": "shinhan", "name": "신한지주", "aliases": ["신한지주", "신한은행", "신한금융", "Shinhan"], "type": "large", "industry": "금융/은행", "logo": "SH"},
    {"id": "hanwha_ocean", "name": "한화오션", "aliases": ["한화오션", "대우조선", "Hanwha Ocean"], "type": "large", "industry": "조선", "logo": "HO"},
    {"id": "hyundai_mobis", "name": "현대모비스", "aliases": ["현대모비스", "모비스", "Mobis"], "type": "large", "industry": "자동차부품", "logo": "HM"},
    {"id": "samsung_life", "name": "삼성생명", "aliases": ["삼성생명", "Samsung Life"], "type": "large", "industry": "보험", "logo": "SL"},
    {"id": "kepco", "name": "한국전력", "aliases": ["한국전력", "한전", "KEPCO"], "type": "public", "industry": "전력/에너지", "logo": "KP"},
    {"id": "hd_ksoe", "name": "HD한국조선해양", "aliases": ["HD한국조선해양", "한국조선해양", "KSOE"], "type": "large", "industry": "조선", "logo": "HK"},
    {"id": "hd_electric", "name": "HD현대일렉트릭", "aliases": ["HD현대일렉트릭", "현대일렉트릭"], "type": "large", "industry": "전기장비", "logo": "HE"},
    {"id": "kakao", "name": "카카오", "aliases": ["카카오", "Kakao", "kakao", "다음카카오"], "type": "large", "industry": "IT/플랫폼", "logo": "K"},
    {"id": "hana_financial", "name": "하나금융지주", "aliases": ["하나금융", "하나은행", "Hana"], "type": "large", "industry": "금융/은행", "logo": "HN"},
    {"id": "posco_holdings", "name": "POSCO홀딩스", "aliases": ["POSCO홀딩스", "포스코", "POSCO", "posco"], "type": "large", "industry": "철강/지주", "logo": "PS"},
    {"id": "korea_zinc", "name": "고려아연", "aliases": ["고려아연", "Korea Zinc"], "type": "large", "industry": "비철금속", "logo": "KZ"},
    {"id": "alteogen", "name": "알테오젠", "aliases": ["알테오젠", "Alteogen"], "type": "mid", "industry": "바이오/제약", "logo": "AT"},
    {"id": "lg_chem", "name": "LG화학", "aliases": ["LG화학", "엘지화학", "LG Chem"], "type": "large", "industry": "화학/소재", "logo": "LC"},
    {"id": "samsung_fire", "name": "삼성화재", "aliases": ["삼성화재", "Samsung Fire"], "type": "large", "industry": "보험", "logo": "SF"},
    {"id": "samsung_sdi", "name": "삼성SDI", "aliases": ["삼성SDI", "Samsung SDI"], "type": "large", "industry": "2차전지", "logo": "SD"},
    {"id": "samsung_heavy", "name": "삼성중공업", "aliases": ["삼성중공업", "Samsung Heavy"], "type": "large", "industry": "조선", "logo": "SH"},
    {"id": "woori_financial", "name": "우리금융지주", "aliases": ["우리금융", "우리은행", "Woori"], "type": "large", "industry": "금융/은행", "logo": "WR"},
    {"id": "hyundai_rotem", "name": "현대로템", "aliases": ["현대로템", "Hyundai Rotem"], "type": "large", "industry": "방산/철도", "logo": "HR"},
    {"id": "meritz_financial", "name": "메리츠금융지주", "aliases": ["메리츠금융", "메리츠", "Meritz"], "type": "large", "industry": "금융/보험", "logo": "MR"},
    {"id": "hmm", "name": "HMM", "aliases": ["HMM", "현대상선", "에이치엠엠"], "type": "large", "industry": "해운", "logo": "HM"},
    {"id": "samsung_electro", "name": "삼성전기", "aliases": ["삼성전기", "Samsung Electro-Mechanics"], "type": "large", "industry": "전자부품", "logo": "SM"},
    {"id": "sk_holdings", "name": "SK", "aliases": ["SK", "에스케이", "SK그룹"], "type": "large", "industry": "에너지/지주", "logo": "SK"},
    {"id": "sk_innovation", "name": "SK이노베이션", "aliases": ["SK이노베이션", "SK이노", "SKI"], "type": "large", "industry": "에너지/화학", "logo": "SI"},
    {"id": "ktng", "name": "KT&G", "aliases": ["KT&G", "케이티앤지", "ktng"], "type": "large", "industry": "담배/건강기능", "logo": "KG"},
    {"id": "ibk", "name": "IBK기업은행", "aliases": ["IBK기업은행", "기업은행", "IBK"], "type": "public", "industry": "금융/은행", "logo": "IB"},
    {"id": "posco_future", "name": "포스코퓨처엠", "aliases": ["포스코퓨처엠", "포스코케미칼", "POSCO Future M"], "type": "large", "industry": "2차전지소재", "logo": "PF"},
    {"id": "hyosung_heavy", "name": "효성중공업", "aliases": ["효성중공업", "Hyosung Heavy"], "type": "large", "industry": "전력기기/중공업", "logo": "HS"},
    {"id": "lg_elec", "name": "LG전자", "aliases": ["LG전자", "엘지전자", "LG Electronics"], "type": "large", "industry": "전자/가전", "logo": "LE"},
    {"id": "hd_hyundai", "name": "HD현대", "aliases": ["HD현대", "현대그룹"], "type": "large", "industry": "지주/중공업", "logo": "HD"},
    {"id": "ecoprobm", "name": "에코프로비엠", "aliases": ["에코프로비엠", "에코프로BM", "EcoPro BM"], "type": "mid", "industry": "2차전지소재", "logo": "EB"},
    {"id": "hybe", "name": "하이브", "aliases": ["하이브", "HYBE", "빅히트", "Big Hit"], "type": "large", "industry": "엔터테인먼트", "logo": "HY"},
    {"id": "ls_electric", "name": "LS ELECTRIC", "aliases": ["LS ELECTRIC", "LS일렉트릭", "LS산전"], "type": "large", "industry": "전기장비", "logo": "LS"},
    {"id": "hyundai_glovis", "name": "현대글로비스", "aliases": ["현대글로비스", "글로비스", "Glovis"], "type": "large", "industry": "물류", "logo": "GL"},
    {"id": "samsung_sds", "name": "삼성SDS", "aliases": ["삼성SDS", "Samsung SDS"], "type": "large", "industry": "IT서비스", "logo": "SS"},
    {"id": "kt", "name": "KT", "aliases": ["KT", "케이티", "한국통신"], "type": "large", "industry": "통신", "logo": "KT"},
    {"id": "mirae_asset", "name": "미래에셋증권", "aliases": ["미래에셋증권", "미래에셋", "Mirae Asset"], "type": "large", "industry": "증권", "logo": "MA"},
]
