# KOSDAQ 시가총액 상위 1~50 회사 데이터
KOSDAQ_1 = [
    {"id": "ecopro_kd", "name": "에코프로", "aliases": ["에코프로", "EcoPro"], "type": "mid", "industry": "2차전지소재", "logo": "EP"},
    {"id": "alteogen_kd", "name": "알테오젠", "aliases": ["알테오젠", "Alteogen"], "type": "mid", "industry": "바이오/제약", "logo": "AT"},
    {"id": "ecoprobm_kd", "name": "에코프로비엠", "aliases": ["에코프로비엠", "에코프로BM", "EcoPro BM"], "type": "mid", "industry": "2차전지소재", "logo": "EB"},
    {"id": "samchundang_kd", "name": "삼천당제약", "aliases": ["삼천당제약", "삼천당"], "type": "mid", "industry": "제약", "logo": "SD"},
    {"id": "rainbow_kd", "name": "레인보우로보틱스", "aliases": ["레인보우로보틱스", "Rainbow Robotics"], "type": "mid", "industry": "로봇", "logo": "RR"},
    {"id": "abl_bio_kd", "name": "에이비엘바이오", "aliases": ["에이비엘바이오", "ABL Bio"], "type": "mid", "industry": "바이오/제약", "logo": "AB"},
    {"id": "kolon_tissue_kd", "name": "코오롱티슈진", "aliases": ["코오롱티슈진", "Kolon TissueGene"], "type": "mid", "industry": "바이오", "logo": "KT"},
    {"id": "caregen", "name": "케어젠", "aliases": ["케어젠", "CareGen"], "type": "mid", "industry": "바이오/펩타이드", "logo": "CG"},
    {"id": "leeno", "name": "리노공업", "aliases": ["리노공업", "LEENO"], "type": "mid", "industry": "반도체장비/부품", "logo": "LN"},
    {"id": "hlb_kd", "name": "HLB", "aliases": ["HLB", "에이치엘비"], "type": "mid", "industry": "바이오/제약", "logo": "HL"},
    {"id": "ligachem_kd", "name": "리가켐바이오", "aliases": ["리가켐바이오", "LigaChem"], "type": "mid", "industry": "바이오/ADC", "logo": "LB"},
    {"id": "peptron_kd", "name": "펩트론", "aliases": ["펩트론", "Peptron"], "type": "mid", "industry": "바이오/제약", "logo": "PT"},
    {"id": "dnd_pharma", "name": "디앤디파마텍", "aliases": ["디앤디파마텍", "D&D Pharmatech"], "type": "mid", "industry": "바이오/제약", "logo": "DD"},
    {"id": "voronoi", "name": "보로노이", "aliases": ["보로노이", "Voronoi"], "type": "mid", "industry": "바이오/제약", "logo": "VR"},
    {"id": "pharma_research", "name": "파마리서치", "aliases": ["파마리서치", "Pharma Research"], "type": "mid", "industry": "바이오/의료기기", "logo": "PR"},
    {"id": "wonik_ips", "name": "원익IPS", "aliases": ["원익IPS", "Wonik IPS"], "type": "mid", "industry": "반도체장비", "logo": "WI"},
    {"id": "classys", "name": "클래시스", "aliases": ["클래시스", "Classys"], "type": "mid", "industry": "의료기기/뷰티", "logo": "CL"},
    {"id": "mezzion", "name": "메지온", "aliases": ["메지온", "Mezzion"], "type": "mid", "industry": "바이오/제약", "logo": "MZ"},
    {"id": "eo_technics", "name": "이오테크닉스", "aliases": ["이오테크닉스", "EO Technics"], "type": "mid", "industry": "레이저장비", "logo": "EO"},
    {"id": "robotis", "name": "로보티즈", "aliases": ["로보티즈", "ROBOTIS"], "type": "mid", "industry": "로봇", "logo": "RB"},
    {"id": "hpsp", "name": "HPSP", "aliases": ["HPSP", "에이치피에스피"], "type": "mid", "industry": "반도체장비", "logo": "HP"},
    {"id": "isc", "name": "ISC", "aliases": ["ISC", "아이에스씨"], "type": "mid", "industry": "반도체검사장비", "logo": "IS"},
    {"id": "oscotec", "name": "오스코텍", "aliases": ["오스코텍", "Oscotec"], "type": "mid", "industry": "바이오/제약", "logo": "OC"},
    {"id": "apr_kd", "name": "에이피알", "aliases": ["에이피알", "APR", "메디큐브"], "type": "mid", "industry": "뷰티/화장품", "logo": "AP"},
    {"id": "hansol_chem", "name": "한솔케미칼", "aliases": ["한솔케미칼", "Hansol Chemical"], "type": "mid", "industry": "반도체소재/화학", "logo": "HC"},
    {"id": "olix", "name": "올릭스", "aliases": ["올릭스", "OliX"], "type": "mid", "industry": "바이오/RNA", "logo": "OL"},
    {"id": "lnc_bio", "name": "엘앤씨바이오", "aliases": ["엘앤씨바이오", "L&C Bio"], "type": "mid", "industry": "바이오/재생의학", "logo": "LB"},
    {"id": "techwing", "name": "테크윙", "aliases": ["테크윙", "Techwing"], "type": "mid", "industry": "반도체장비", "logo": "TW"},
    {"id": "hugel", "name": "휴젤", "aliases": ["휴젤", "Hugel", "보톡스"], "type": "mid", "industry": "바이오/뷰티", "logo": "HG"},
    {"id": "soulbrain", "name": "솔브레인", "aliases": ["솔브레인", "Soulbrain"], "type": "mid", "industry": "반도체소재/화학", "logo": "SB"},
    {"id": "eugene_tech", "name": "유진테크", "aliases": ["유진테크", "Eugene Technology"], "type": "mid", "industry": "반도체장비", "logo": "YT"},
    {"id": "park_systems", "name": "파크시스템스", "aliases": ["파크시스템스", "Park Systems"], "type": "mid", "industry": "정밀측정장비", "logo": "PK"},
    {"id": "duksan_neolux", "name": "덕산네오룩스", "aliases": ["덕산네오룩스", "Duksan Neolux"], "type": "mid", "industry": "OLED소재", "logo": "DN"},
    {"id": "ad_tech", "name": "에이디테크놀로지", "aliases": ["에이디테크놀로지", "AD Technology"], "type": "mid", "industry": "반도체설계", "logo": "AD"},
    {"id": "tck", "name": "티씨케이", "aliases": ["티씨케이", "TCK"], "type": "mid", "industry": "반도체소재", "logo": "TC"},
    {"id": "psk", "name": "피에스케이", "aliases": ["피에스케이", "PSK"], "type": "mid", "industry": "반도체장비", "logo": "PS"},
    {"id": "jusung_eng", "name": "주성엔지니어링", "aliases": ["주성엔지니어링", "Jusung Engineering"], "type": "mid", "industry": "반도체장비", "logo": "JS"},
    {"id": "celltrion_pharm", "name": "셀트리온제약", "aliases": ["셀트리온제약", "Celltrion Pharm"], "type": "mid", "industry": "바이오/제약", "logo": "CP"},
    {"id": "simmtech", "name": "심텍", "aliases": ["심텍", "Simmtech"], "type": "mid", "industry": "PCB/기판", "logo": "SM"},
    {"id": "hlb_life", "name": "HLB생명과학", "aliases": ["HLB생명과학", "HLB Life Science"], "type": "mid", "industry": "바이오", "logo": "HL"},
    {"id": "dongkuk_pharm", "name": "동국제약", "aliases": ["동국제약", "Dongkuk Pharm"], "type": "mid", "industry": "제약", "logo": "DK"},
    {"id": "nepes", "name": "네패스", "aliases": ["네패스", "Nepes"], "type": "mid", "industry": "반도체패키징", "logo": "NP"},
    {"id": "seegene", "name": "씨젠", "aliases": ["씨젠", "Seegene"], "type": "mid", "industry": "진단/바이오", "logo": "SG"},
    {"id": "sungeel", "name": "성일하이텍", "aliases": ["성일하이텍", "SungEel HiTech"], "type": "mid", "industry": "2차전지리사이클링", "logo": "SH"},
    {"id": "sm_ent", "name": "SM엔터테인먼트", "aliases": ["SM엔터테인먼트", "SM", "에스엠"], "type": "large", "industry": "엔터테인먼트", "logo": "SM"},
    {"id": "interojo", "name": "인터로조", "aliases": ["인터로조", "Interojo"], "type": "mid", "industry": "콘택트렌즈/의료기기", "logo": "IJ"},
    {"id": "cj_enm_kd", "name": "CJ ENM", "aliases": ["CJ ENM", "CJ이엔엠", "tvN"], "type": "large", "industry": "엔터/미디어", "logo": "CE"},
    {"id": "bh_co", "name": "비에이치", "aliases": ["비에이치", "BH"], "type": "mid", "industry": "FPCB/전자부품", "logo": "BH"},
    {"id": "jyp_ent", "name": "JYP엔터테인먼트", "aliases": ["JYP", "JYP엔터", "JYP엔터테인먼트"], "type": "mid", "industry": "엔터테인먼트", "logo": "JY"},
    {"id": "silicon2", "name": "실리콘투", "aliases": ["실리콘투", "Silicon2"], "type": "mid", "industry": "뷰티/이커머스", "logo": "S2"},
]
