-- Job Choice OS — MySQL Schema (한국형 표준 명명 규칙)
-- 테이블 접두사 T, 전 컬럼 대문자, 분류어 종결, 감사 컬럼 4종(INS_ID/INS_DTM/MOD_ID/MOD_DTM),
-- 모든 PK는 INT AUTO_INCREMENT, FK는 INT.
-- UTF-8 Korean support
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- ━━ REFERENCE DATA ━━

CREATE TABLE IF NOT EXISTS TCOMPANY_TYPE (
  COMP_TP_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '기업유형 PK',
  COMP_TP_CD VARCHAR(20) NOT NULL UNIQUE COMMENT '기업유형 코드 (large, startup, mid, foreign, public, freelance)',
  COMP_TP_NM VARCHAR(20) NOT NULL COMMENT '표시 라벨 (대기업, 스타트업 등)',
  GROWTH_RATE_VAL DECIMAL(5,4) NOT NULL COMMENT '연평균 연봉 상승률 (0.0350 = 3.5%)',
  GROWTH_LABEL_NM VARCHAR(50) NOT NULL COMMENT '성장률 설명 텍스트',
  STABILITY_SCORE_NO TINYINT NOT NULL COMMENT '고용 안정성 점수 (1~100)',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TCOMPANY (
  COMP_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '회사 PK',
  COMP_ENG_NM VARCHAR(30) NOT NULL UNIQUE COMMENT '회사 영문 식별명 (cj, samsung_elec 등 — 과거 id)',
  COMP_NM VARCHAR(100) NOT NULL UNIQUE COMMENT '회사 정식 명칭',
  COMP_TP_ID INT NOT NULL COMMENT '기업유형 FK',
  INDUSTRY_NM VARCHAR(50) COMMENT '산업 분류 (식품/유통, 핀테크 등)',
  LOGO_NM VARCHAR(10) COMMENT '로고 약어 (CJ, T 등)',
  WORK_STYLE_VAL JSON COMMENT '근무 형태 {remote, flex, unlimitedPTO, refreshLeave, overtime}',
  CAREERS_BENEFIT_URL VARCHAR(500) COMMENT '채용 홈페이지 복지 페이지 URL',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (COMP_TP_ID) REFERENCES TCOMPANY_TYPE(COMP_TP_ID),
  FULLTEXT INDEX idx_comp_nm (COMP_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TCOMPANY_ALIAS (
  ALIAS_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '별칭 PK',
  COMP_ID INT NOT NULL COMMENT '회사 FK',
  ALIAS_NM VARCHAR(100) NOT NULL COMMENT '검색용 별칭 (CJ, 씨제이, cj 등)',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (COMP_ID) REFERENCES TCOMPANY(COMP_ID) ON DELETE CASCADE,
  UNIQUE KEY uq_comp_alias (COMP_ID, ALIAS_NM),
  INDEX idx_alias_nm (ALIAS_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TCOMPANY_BENEFIT (
  BENEFIT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '복지항목 PK',
  COMP_ID INT NOT NULL COMMENT '회사 FK',
  BENEFIT_CD VARCHAR(30) NOT NULL COMMENT '복지 코드 (meal, fitness, housing 등)',
  BENEFIT_NM VARCHAR(100) NOT NULL COMMENT '복지 표시명 (식대, 헬스장 등)',
  BENEFIT_AMT INT DEFAULT NULL COMMENT '연간 환산 금액 (만원, 정성적 항목은 NULL)',
  BENEFIT_CTGR_CD VARCHAR(20) NOT NULL COMMENT '복지 카테고리 (compensation, flexibility, work_env, time_off, health, family, growth, leisure, perks)',
  BADGE_CD VARCHAR(10) DEFAULT 'est' COMMENT '데이터 신뢰도 (est: 추정, official: 공식)',
  NOTE_CTNT VARCHAR(200) COMMENT '복지 상세 설명',
  QUAL_YN BOOLEAN DEFAULT FALSE COMMENT '정성적 복지 여부 (TRUE: 금액 환산 불가)',
  QUAL_DESC_CTNT VARCHAR(500) COMMENT '정성적 복지 상세 텍스트',
  SORT_ORDER_NO SMALLINT DEFAULT 0 COMMENT '표시 정렬 순서',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (COMP_ID) REFERENCES TCOMPANY(COMP_ID) ON DELETE CASCADE,
  UNIQUE KEY uq_comp_benefit (COMP_ID, BENEFIT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TBENEFIT_PRESET (
  PRESET_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '프리셋 PK',
  COMP_TP_ID INT NOT NULL COMMENT '기업유형 FK',
  BENEFIT_CD VARCHAR(30) NOT NULL COMMENT '복지 코드',
  BENEFIT_NM VARCHAR(100) NOT NULL COMMENT '복지 표시명',
  BENEFIT_AMT INT DEFAULT NULL COMMENT '연간 환산 금액 (만원, 정성적 항목은 NULL)',
  BENEFIT_CTGR_CD VARCHAR(20) NOT NULL COMMENT '복지 카테고리 (compensation, flexibility, work_env, time_off, health, family, growth, leisure, perks)',
  BADGE_CD VARCHAR(10) DEFAULT 'est' COMMENT '데이터 신뢰도 (est, official)',
  DEFAULT_CHECKED_YN BOOLEAN DEFAULT TRUE COMMENT '기본 체크 상태',
  SORT_ORDER_NO SMALLINT DEFAULT 0 COMMENT '표시 정렬 순서',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (COMP_TP_ID) REFERENCES TCOMPANY_TYPE(COMP_TP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ━━ PROFILER DATA ━━

CREATE TABLE IF NOT EXISTS TPROFILE (
  PROFILE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '프로필 PK',
  PROFILE_CD VARCHAR(20) NOT NULL UNIQUE COMMENT '프로필 코드 (balanced, growth_seeker 등)',
  PROFILE_NM VARCHAR(20) NOT NULL COMMENT '프로필 유형명 (균형파, 성장파 등)',
  PROFILE_DESC_CTNT TEXT NOT NULL COMMENT '프로필 상세 설명',
  MAP_PRIORITY_CD VARCHAR(20) NOT NULL COMMENT '매핑 우선순위 키 (salary, wlb, benefits, brand)',
  VEC_VAL JSON NOT NULL COMMENT '6차원 벡터 {compensation, security, growth, autonomy, impact, flexibility}',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TPROFILE_JOB_FIT (
  FIT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '직무적합도 PK',
  PROFILE_ID INT NOT NULL COMMENT '프로필 FK',
  SCENARIO_CD VARCHAR(20) NOT NULL COMMENT '시나리오 코드 (tech, design, pm, biz 등)',
  FIT_CTNT TEXT NOT NULL COMMENT '적합한 점 설명',
  CAUTION_CTNT TEXT NOT NULL COMMENT '주의할 점 설명',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (PROFILE_ID) REFERENCES TPROFILE(PROFILE_ID),
  UNIQUE INDEX idx_profile_scenario (PROFILE_ID, SCENARIO_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TJOB_GROUP (
  JOB_GROUP_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '직군 그룹 PK',
  JOB_GROUP_NM VARCHAR(30) NOT NULL COMMENT '그룹 표시명 (개발, 디자인, 기획 등)',
  COLOR_CD VARCHAR(10) NOT NULL COMMENT 'UI 색상 코드 (#4A9B8E 등)',
  SORT_ORDER_NO TINYINT NOT NULL COMMENT '표시 정렬 순서',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TJOB (
  JOB_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '직무 PK',
  JOB_CD VARCHAR(30) NOT NULL UNIQUE COMMENT '직무 코드 (fe_dev, pm 등)',
  JOB_GROUP_ID INT NOT NULL COMMENT '직군 그룹 FK',
  JOB_NM VARCHAR(30) NOT NULL COMMENT '직무 표시명 (프론트엔드, PM 등)',
  ICON_NM VARCHAR(10) NOT NULL COMMENT '직무 아이콘 이모지',
  SCENARIO_CD VARCHAR(20) NOT NULL COMMENT '시나리오 코드 (tech, design, pm, biz)',
  SORT_ORDER_NO TINYINT NOT NULL COMMENT '표시 정렬 순서',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (JOB_GROUP_ID) REFERENCES TJOB_GROUP(JOB_GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TPROFILER_QUESTION (
  QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '질문 PK',
  QUESTION_NO INT NOT NULL UNIQUE COMMENT '질문 번호 (원본 1..N)',
  QUESTION_LABEL_NM VARCHAR(30) NOT NULL COMMENT '질문 짧은 라벨',
  OPTION_A_TITLE_NM VARCHAR(50) NOT NULL COMMENT '선택지 A 제목',
  OPTION_A_FX_VAL JSON NOT NULL COMMENT '선택지 A 점수 효과 {dim: delta}',
  OPTION_B_TITLE_NM VARCHAR(50) NOT NULL COMMENT '선택지 B 제목',
  OPTION_B_FX_VAL JSON NOT NULL COMMENT '선택지 B 점수 효과 {dim: delta}',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TQUESTION_SCENARIO (
  QUESTION_SCENARIO_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '시나리오별 질문 PK',
  QUESTION_ID INT NOT NULL COMMENT '질문 FK',
  SCENARIO_CD VARCHAR(20) NOT NULL COMMENT '시나리오 코드 (tech, design, pm, biz)',
  DESC_A_CTNT TEXT NOT NULL COMMENT '선택지 A 시나리오별 상세 설명',
  DESC_B_CTNT TEXT NOT NULL COMMENT '선택지 B 시나리오별 상세 설명',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (QUESTION_ID) REFERENCES TPROFILER_QUESTION(QUESTION_ID),
  UNIQUE INDEX idx_q_scenario (QUESTION_ID, SCENARIO_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ━━ MEMBER & USER DATA ━━

CREATE TABLE IF NOT EXISTS TMEMBER (
  MBR_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 PK',
  EMAIL_ADDR VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일 주소 (로그인 ID)',
  PWD_HASH_VAL VARCHAR(255) COMMENT 'bcrypt 해시된 비밀번호 (소셜 로그인 시 NULL)',
  MBR_NM VARCHAR(50) COMMENT '사용자 표시 이름',
  JOB_NM VARCHAR(50) COMMENT '선택한 직군명 (백엔드 개발, PM 등)',
  ROLE_CD VARCHAR(20) DEFAULT 'user' COMMENT '사용자 역할 (user, admin)',
  LOGIN_PROVIDER_CD VARCHAR(20) DEFAULT 'local' COMMENT '인증 제공자 (local, kakao, naver, google)',
  COMP_EMAIL_ADDR VARCHAR(255) COMMENT '인증된 회사 이메일 주소',
  COMP_EMAIL_VRFC_YN VARCHAR(1) DEFAULT 'N' COMMENT '회사 이메일 인증 여부 (Y/N)',
  VRFC_COMP_ID INT DEFAULT NULL COMMENT '회사 이메일로 인증된 회사 FK (companies.comp_id)',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '가입 일시 (입력 일시)',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  INDEX idx_email_addr (EMAIL_ADDR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TPROFILER_RESULT (
  RESULT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '프로파일러 결과 PK',
  MBR_ID INT NOT NULL COMMENT '사용자 FK',
  JOB_ID INT COMMENT '선택한 직무 FK',
  SCORES_VAL JSON NOT NULL COMMENT '6차원 점수 {compensation, security, growth, autonomy, impact, flexibility}',
  PROFILE_ID INT NOT NULL COMMENT '매칭된 프로필 FK',
  SIMILARITY_VAL DECIMAL(5,4) NOT NULL COMMENT '프로필 유사도 (0.0000~1.0000)',
  ANSWERS_VAL JSON NOT NULL COMMENT '사용자 답변 배열 [{q, choice}]',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '결과 생성 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (MBR_ID) REFERENCES TMEMBER(MBR_ID) ON DELETE CASCADE,
  FOREIGN KEY (JOB_ID) REFERENCES TJOB(JOB_ID),
  FOREIGN KEY (PROFILE_ID) REFERENCES TPROFILE(PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TCOMPARISON (
  COMPARISON_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '비교 PK',
  MBR_ID INT NOT NULL COMMENT '사용자 FK',
  COMP_A_NM VARCHAR(100) COMMENT 'A측(현직) 회사명',
  COMP_A_TP_CD VARCHAR(20) NOT NULL COMMENT 'A측 기업유형 코드',
  SALARY_A_MIN_AMT INT COMMENT 'A측 연봉 하한 (만원)',
  SALARY_A_MAX_AMT INT COMMENT 'A측 연봉 상한 (만원)',
  COMMUTE_A_MIN_NO INT DEFAULT 0 COMMENT 'A측 편도 통근 시간 (분)',
  WORK_STYLE_A_VAL JSON COMMENT 'A측 근무 형태 {ot, wage, remote, flex}',
  BENEFITS_A_VAL JSON COMMENT 'A측 복리후생 배열 [{ben_key, name, val, cat, checked}]',
  COMP_B_NM VARCHAR(100) COMMENT 'B측(이직처) 회사명',
  COMP_B_TP_CD VARCHAR(20) NOT NULL COMMENT 'B측 기업유형 코드',
  SALARY_RATE_VAL INT COMMENT '연봉 인상률 (%)',
  COMMUTE_B_MIN_NO INT DEFAULT 0 COMMENT 'B측 편도 통근 시간 (분)',
  WORK_STYLE_B_VAL JSON COMMENT 'B측 근무 형태',
  BENEFITS_B_VAL JSON COMMENT 'B측 복리후생 배열',
  PRIORITY_CD VARCHAR(20) NOT NULL COMMENT '최우선 기준 코드 (salary, wlb, benefits, brand)',
  SACRIFICE_CD VARCHAR(20) COMMENT '포기 가능 기준 코드',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '비교 생성 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (MBR_ID) REFERENCES TMEMBER(MBR_ID) ON DELETE CASCADE,
  INDEX idx_mbr_ins (MBR_ID, INS_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ━━ SOCIAL AUTH & EMAIL VERIFICATION ━━

CREATE TABLE IF NOT EXISTS TSOCIAL_ACCOUNT (
  SOCIAL_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '소셜 계정 PK',
  MBR_ID INT NOT NULL COMMENT '사용자 FK',
  PROVIDER_CD VARCHAR(20) NOT NULL COMMENT '소셜 제공자 코드 (kakao, naver, google)',
  PROVIDER_USER_ID VARCHAR(255) NOT NULL COMMENT '제공자 고유 사용자 ID',
  EMAIL_ADDR VARCHAR(255) COMMENT '소셜 계정 이메일 주소',
  SOCIAL_NM VARCHAR(100) COMMENT '소셜 계정 이름',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '연동 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  UNIQUE KEY uq_provider_user (PROVIDER_CD, PROVIDER_USER_ID),
  FOREIGN KEY (MBR_ID) REFERENCES TMEMBER(MBR_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TEMAIL_VERIFICATION (
  VERIFY_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '이메일 인증 PK',
  MBR_ID INT NOT NULL COMMENT '사용자 FK',
  COMP_ID INT NOT NULL COMMENT '인증 대상 회사 FK (companies.comp_id)',
  EMAIL_ADDR VARCHAR(255) NOT NULL COMMENT '인증 대상 이메일 주소',
  TOKEN_VAL VARCHAR(255) NOT NULL COMMENT '인증 토큰 값',
  EXPIRES_DTM DATETIME NOT NULL COMMENT '만료 일시 (24시간)',
  VERIFIED_DTM DATETIME COMMENT '인증 완료 일시',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  UNIQUE KEY uq_token (TOKEN_VAL),
  FOREIGN KEY (MBR_ID) REFERENCES TMEMBER(MBR_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ━━ LANDING FEED DATA ━━

CREATE TABLE IF NOT EXISTS TCOMPARISON_FEED (
  FEED_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '피드 PK',
  COMPARISON_ID INT NOT NULL COMMENT '비교 FK',
  JOB_CTGR_NM VARCHAR(30) COMMENT '직무 카테고리명 (개발자, PM, 디자이너 등)',
  COMP_A_DISP_NM VARCHAR(100) COMMENT 'A측 표시용 회사명',
  COMP_A_TP_CD VARCHAR(20) NOT NULL COMMENT 'A측 기업유형 코드',
  COMP_B_DISP_NM VARCHAR(100) COMMENT 'B측 표시용 회사명',
  COMP_B_TP_CD VARCHAR(20) NOT NULL COMMENT 'B측 기업유형 코드',
  HEADLINE_CTNT VARCHAR(300) NOT NULL COMMENT '비교 결과 한줄 요약',
  DETAIL_CTNT VARCHAR(500) COMMENT '부가 설명 텍스트',
  METRIC_VAL_CTNT VARCHAR(30) COMMENT '핵심 수치 (+18.4%, +1,240만 등)',
  METRIC_LABEL_NM VARCHAR(30) COMMENT '수치 라벨 (시간당 가치, 3년 복지 누적 등)',
  METRIC_TYPE_CD VARCHAR(10) DEFAULT 'neu' COMMENT '수치 방향 코드 (up, down, neu)',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '피드 생성 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  FOREIGN KEY (COMPARISON_ID) REFERENCES TCOMPARISON(COMPARISON_ID) ON DELETE CASCADE,
  INDEX idx_feed_ins (INS_DTM DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TDAILY_STAT (
  STAT_DT DATE PRIMARY KEY COMMENT '통계 날짜',
  COMPARISON_NO INT DEFAULT 0 COMMENT '해당일 비교 실행 횟수',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '입력 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TPOPULAR_CASE (
  CASE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '인기 사례 PK',
  CASE_TYPE_CD VARCHAR(20) NOT NULL COMMENT '사례 유형 코드 (company, scenario)',
  CURRENT_COMP_NM VARCHAR(50) NOT NULL COMMENT '현직(A측) 회사명',
  CURRENT_COMP_TP_CD VARCHAR(20) NOT NULL COMMENT '현직 기업유형 코드',
  CURRENT_SUB_NM VARCHAR(30) COMMENT '현직 부제 (대기업, 안정성 등)',
  OFFER_COMP_NM VARCHAR(50) NOT NULL COMMENT '이직처(B측) 회사명',
  OFFER_COMP_TP_CD VARCHAR(20) NOT NULL COMMENT '이직처 기업유형 코드',
  OFFER_SUB_NM VARCHAR(30) COMMENT '이직처 부제',
  POINTS_VAL JSON COMMENT '비교 포인트 배열 ["포인트1", "포인트2", "포인트3"]',
  VIEW_NO INT DEFAULT 0 COMMENT '조회 수',
  COMPARISON_NO INT DEFAULT 0 COMMENT '비교 실행 수',
  ACTIVE_YN BOOLEAN DEFAULT TRUE COMMENT '활성 상태 (TRUE: 노출, FALSE: 숨김)',
  INS_ID INT COMMENT '입력자 ID',
  INS_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '사례 생성 일시',
  MOD_ID INT COMMENT '수정자 ID',
  MOD_DTM TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  INDEX idx_active_comparison (ACTIVE_YN, COMPARISON_NO DESC),
  UNIQUE KEY uq_case_pair (CASE_TYPE_CD, CURRENT_COMP_NM, OFFER_COMP_NM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
